# Google Cloud Build — CI/CD pipeline for G-Tech
# Triggers on push to 'master' branch (configure in Cloud Console)
#
# Usage:
#   gcloud builds submit --config cloudbuild.yaml .
#   OR connect GitHub repo in Cloud Build > Triggers

substitutions:
  _REGION: us-central1
  _REPO: g-tech
  _SERVICE: g-tech
  _IMAGE: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --tag
      - '${_IMAGE}:$COMMIT_SHA'
      - --tag
      - '${_IMAGE}:latest'
      - --cache-from
      - '${_IMAGE}:latest'
      - .
    id: 'build-image'

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_IMAGE}']
    id: 'push-image'
    waitFor: ['build-image']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - --image
      - '${_IMAGE}:$COMMIT_SHA'
      - --region
      - '${_REGION}'
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 512Mi
      - --cpu
      - '1'
      - --min-instances
      - '0'
      - --max-instances
      - '10'
      - --port
      - '3000'
      - --set-env-vars
      - NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1
    id: 'deploy'
    waitFor: ['push-image']

images:
  - '${_IMAGE}:$COMMIT_SHA'
  - '${_IMAGE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
